// source: provisioner.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var stake_pb = require('./stake_pb.js');
goog.object.extend(proto, stake_pb);
goog.exportSymbol('proto.rusk.Provisioner', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rusk.Provisioner = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rusk.Provisioner.repeatedFields_, null);
};
goog.inherits(proto.rusk.Provisioner, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rusk.Provisioner.displayName = 'proto.rusk.Provisioner';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rusk.Provisioner.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rusk.Provisioner.prototype.toObject = function(opt_includeInstance) {
  return proto.rusk.Provisioner.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rusk.Provisioner} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rusk.Provisioner.toObject = function(includeInstance, msg) {
  var f, obj = {
    publicKeyBls: msg.getPublicKeyBls_asB64(),
    rawPublicKeyBls: msg.getRawPublicKeyBls_asB64(),
    stakesList: jspb.Message.toObjectList(msg.getStakesList(),
    stake_pb.Stake.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rusk.Provisioner}
 */
proto.rusk.Provisioner.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rusk.Provisioner;
  return proto.rusk.Provisioner.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rusk.Provisioner} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rusk.Provisioner}
 */
proto.rusk.Provisioner.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPublicKeyBls(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawPublicKeyBls(value);
      break;
    case 3:
      var value = new stake_pb.Stake;
      reader.readMessage(value,stake_pb.Stake.deserializeBinaryFromReader);
      msg.addStakes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rusk.Provisioner.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rusk.Provisioner.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rusk.Provisioner} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rusk.Provisioner.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPublicKeyBls_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getRawPublicKeyBls_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getStakesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      stake_pb.Stake.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes public_key_bls = 1;
 * @return {string}
 */
proto.rusk.Provisioner.prototype.getPublicKeyBls = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes public_key_bls = 1;
 * This is a type-conversion wrapper around `getPublicKeyBls()`
 * @return {string}
 */
proto.rusk.Provisioner.prototype.getPublicKeyBls_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPublicKeyBls()));
};


/**
 * optional bytes public_key_bls = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPublicKeyBls()`
 * @return {!Uint8Array}
 */
proto.rusk.Provisioner.prototype.getPublicKeyBls_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPublicKeyBls()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.rusk.Provisioner} returns this
 */
proto.rusk.Provisioner.prototype.setPublicKeyBls = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes raw_public_key_bls = 2;
 * @return {string}
 */
proto.rusk.Provisioner.prototype.getRawPublicKeyBls = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes raw_public_key_bls = 2;
 * This is a type-conversion wrapper around `getRawPublicKeyBls()`
 * @return {string}
 */
proto.rusk.Provisioner.prototype.getRawPublicKeyBls_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawPublicKeyBls()));
};


/**
 * optional bytes raw_public_key_bls = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawPublicKeyBls()`
 * @return {!Uint8Array}
 */
proto.rusk.Provisioner.prototype.getRawPublicKeyBls_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawPublicKeyBls()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.rusk.Provisioner} returns this
 */
proto.rusk.Provisioner.prototype.setRawPublicKeyBls = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * repeated Stake stakes = 3;
 * @return {!Array<!proto.rusk.Stake>}
 */
proto.rusk.Provisioner.prototype.getStakesList = function() {
  return /** @type{!Array<!proto.rusk.Stake>} */ (
    jspb.Message.getRepeatedWrapperField(this, stake_pb.Stake, 3));
};


/**
 * @param {!Array<!proto.rusk.Stake>} value
 * @return {!proto.rusk.Provisioner} returns this
*/
proto.rusk.Provisioner.prototype.setStakesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.rusk.Stake=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rusk.Stake}
 */
proto.rusk.Provisioner.prototype.addStakes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.rusk.Stake, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rusk.Provisioner} returns this
 */
proto.rusk.Provisioner.prototype.clearStakesList = function() {
  return this.setStakesList([]);
};


goog.object.extend(exports, proto.rusk);
