// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blindbid.proto

package rusk

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BlindBidServiceMock struct{}

func (m *BlindBidServiceMock) GenerateScore(ctx context.Context, req *GenerateScoreRequest) (*GenerateScoreResponse, error) {
	res :=
		&GenerateScoreResponse{
			BlindbidProof:  &Proof{},
			Score:          &BlsScalar{},
			ProverIdentity: &BlsScalar{},
		}
	return res, nil
}
func (m *BlindBidServiceMock) VerifyScore(ctx context.Context, req *VerifyScoreRequest) (*VerifyScoreResponse, error) {
	res :=
		&VerifyScoreResponse{
			Success: false,
		}
	return res, nil
}
