// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.4
// source: keys.proto

package _

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SecretKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *JubJubScalar `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B *JubJubScalar `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *SecretKey) Reset() {
	*x = SecretKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKey) ProtoMessage() {}

func (x *SecretKey) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKey.ProtoReflect.Descriptor instead.
func (*SecretKey) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{0}
}

func (x *SecretKey) GetA() *JubJubScalar {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *SecretKey) GetB() *JubJubScalar {
	if x != nil {
		return x.B
	}
	return nil
}

type ViewKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A  *JubJubScalar     `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	BG *JubJubCompressed `protobuf:"bytes,2,opt,name=b_g,json=bG,proto3" json:"b_g,omitempty"`
}

func (x *ViewKey) Reset() {
	*x = ViewKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewKey) ProtoMessage() {}

func (x *ViewKey) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewKey.ProtoReflect.Descriptor instead.
func (*ViewKey) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{1}
}

func (x *ViewKey) GetA() *JubJubScalar {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *ViewKey) GetBG() *JubJubCompressed {
	if x != nil {
		return x.BG
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AG *JubJubCompressed `protobuf:"bytes,1,opt,name=a_g,json=aG,proto3" json:"a_g,omitempty"`
	BG *JubJubCompressed `protobuf:"bytes,2,opt,name=b_g,json=bG,proto3" json:"b_g,omitempty"`
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keys_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{2}
}

func (x *PublicKey) GetAG() *JubJubCompressed {
	if x != nil {
		return x.AG
	}
	return nil
}

func (x *PublicKey) GetBG() *JubJubCompressed {
	if x != nil {
		return x.BG
	}
	return nil
}

type StealthAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RG  *JubJubCompressed `protobuf:"bytes,1,opt,name=r_g,json=rG,proto3" json:"r_g,omitempty"`
	PkR *JubJubCompressed `protobuf:"bytes,2,opt,name=pk_r,json=pkR,proto3" json:"pk_r,omitempty"`
}

func (x *StealthAddress) Reset() {
	*x = StealthAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keys_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StealthAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealthAddress) ProtoMessage() {}

func (x *StealthAddress) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealthAddress.ProtoReflect.Descriptor instead.
func (*StealthAddress) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{3}
}

func (x *StealthAddress) GetRG() *JubJubCompressed {
	if x != nil {
		return x.RG
	}
	return nil
}

func (x *StealthAddress) GetPkR() *JubJubCompressed {
	if x != nil {
		return x.PkR
	}
	return nil
}

var File_keys_proto protoreflect.FileDescriptor

var file_keys_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x75,
	0x73, 0x6b, 0x1a, 0x12, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x72, 0x75, 0x73, 0x6b, 0x2e, 0x4a, 0x75, 0x62, 0x4a, 0x75, 0x62, 0x53, 0x63, 0x61, 0x6c,
	0x61, 0x72, 0x52, 0x01, 0x61, 0x12, 0x20, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x72, 0x75, 0x73, 0x6b, 0x2e, 0x4a, 0x75, 0x62, 0x4a, 0x75, 0x62, 0x53, 0x63,
	0x61, 0x6c, 0x61, 0x72, 0x52, 0x01, 0x62, 0x22, 0x54, 0x0a, 0x07, 0x56, 0x69, 0x65, 0x77, 0x4b,
	0x65, 0x79, 0x12, 0x20, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x72, 0x75, 0x73, 0x6b, 0x2e, 0x4a, 0x75, 0x62, 0x4a, 0x75, 0x62, 0x53, 0x63, 0x61, 0x6c, 0x61,
	0x72, 0x52, 0x01, 0x61, 0x12, 0x27, 0x0a, 0x03, 0x62, 0x5f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x73, 0x6b, 0x2e, 0x4a, 0x75, 0x62, 0x4a, 0x75, 0x62, 0x43,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x02, 0x62, 0x47, 0x22, 0x5d, 0x0a,
	0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x03, 0x61, 0x5f,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x73, 0x6b, 0x2e, 0x4a,
	0x75, 0x62, 0x4a, 0x75, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52,
	0x02, 0x61, 0x47, 0x12, 0x27, 0x0a, 0x03, 0x62, 0x5f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x72, 0x75, 0x73, 0x6b, 0x2e, 0x4a, 0x75, 0x62, 0x4a, 0x75, 0x62, 0x43, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x02, 0x62, 0x47, 0x22, 0x64, 0x0a, 0x0e,
	0x53, 0x74, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x27,
	0x0a, 0x03, 0x72, 0x5f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75,
	0x73, 0x6b, 0x2e, 0x4a, 0x75, 0x62, 0x4a, 0x75, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x64, 0x52, 0x02, 0x72, 0x47, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x6b, 0x5f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x73, 0x6b, 0x2e, 0x4a, 0x75, 0x62,
	0x4a, 0x75, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x03, 0x70,
	0x6b, 0x52, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x75, 0x73, 0x6b, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x72, 0x75,
	0x73, 0x6b, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_keys_proto_rawDescOnce sync.Once
	file_keys_proto_rawDescData = file_keys_proto_rawDesc
)

func file_keys_proto_rawDescGZIP() []byte {
	file_keys_proto_rawDescOnce.Do(func() {
		file_keys_proto_rawDescData = protoimpl.X.CompressGZIP(file_keys_proto_rawDescData)
	})
	return file_keys_proto_rawDescData
}

var file_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_keys_proto_goTypes = []interface{}{
	(*SecretKey)(nil),        // 0: rusk.SecretKey
	(*ViewKey)(nil),          // 1: rusk.ViewKey
	(*PublicKey)(nil),        // 2: rusk.PublicKey
	(*StealthAddress)(nil),   // 3: rusk.StealthAddress
	(*JubJubScalar)(nil),     // 4: rusk.JubJubScalar
	(*JubJubCompressed)(nil), // 5: rusk.JubJubCompressed
}
var file_keys_proto_depIdxs = []int32{
	4, // 0: rusk.SecretKey.a:type_name -> rusk.JubJubScalar
	4, // 1: rusk.SecretKey.b:type_name -> rusk.JubJubScalar
	4, // 2: rusk.ViewKey.a:type_name -> rusk.JubJubScalar
	5, // 3: rusk.ViewKey.b_g:type_name -> rusk.JubJubCompressed
	5, // 4: rusk.PublicKey.a_g:type_name -> rusk.JubJubCompressed
	5, // 5: rusk.PublicKey.b_g:type_name -> rusk.JubJubCompressed
	5, // 6: rusk.StealthAddress.r_g:type_name -> rusk.JubJubCompressed
	5, // 7: rusk.StealthAddress.pk_r:type_name -> rusk.JubJubCompressed
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_keys_proto_init() }
func file_keys_proto_init() {
	if File_keys_proto != nil {
		return
	}
	file_basic_fields_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_keys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keys_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keys_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StealthAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keys_proto_goTypes,
		DependencyIndexes: file_keys_proto_depIdxs,
		MessageInfos:      file_keys_proto_msgTypes,
	}.Build()
	File_keys_proto = out.File
	file_keys_proto_rawDesc = nil
	file_keys_proto_goTypes = nil
	file_keys_proto_depIdxs = nil
}
