// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rusk.proto

package rusk

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VerifyStateTransitionRequest struct {
	Txs                  []*Transaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	Height               uint64         `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Seed                 []byte         `protobuf:"bytes,3,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VerifyStateTransitionRequest) Reset()         { *m = VerifyStateTransitionRequest{} }
func (m *VerifyStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyStateTransitionRequest) ProtoMessage()    {}
func (*VerifyStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{0}
}
func (m *VerifyStateTransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyStateTransitionRequest.Unmarshal(m, b)
}
func (m *VerifyStateTransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyStateTransitionRequest.Marshal(b, m, deterministic)
}
func (m *VerifyStateTransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyStateTransitionRequest.Merge(m, src)
}
func (m *VerifyStateTransitionRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyStateTransitionRequest.Size(m)
}
func (m *VerifyStateTransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyStateTransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyStateTransitionRequest proto.InternalMessageInfo

func (m *VerifyStateTransitionRequest) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *VerifyStateTransitionRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VerifyStateTransitionRequest) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type VerifyStateTransitionResponse struct {
	FailedCalls          []uint64 `protobuf:"fixed64,1,rep,packed,name=failed_calls,json=failedCalls,proto3" json:"failed_calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyStateTransitionResponse) Reset()         { *m = VerifyStateTransitionResponse{} }
func (m *VerifyStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyStateTransitionResponse) ProtoMessage()    {}
func (*VerifyStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{1}
}
func (m *VerifyStateTransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyStateTransitionResponse.Unmarshal(m, b)
}
func (m *VerifyStateTransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyStateTransitionResponse.Marshal(b, m, deterministic)
}
func (m *VerifyStateTransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyStateTransitionResponse.Merge(m, src)
}
func (m *VerifyStateTransitionResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyStateTransitionResponse.Size(m)
}
func (m *VerifyStateTransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyStateTransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyStateTransitionResponse proto.InternalMessageInfo

func (m *VerifyStateTransitionResponse) GetFailedCalls() []uint64 {
	if m != nil {
		return m.FailedCalls
	}
	return nil
}

type ExecuteStateTransitionRequest struct {
	Txs                  []*Transaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	Height               uint64         `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Seed                 []byte         `protobuf:"bytes,3,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExecuteStateTransitionRequest) Reset()         { *m = ExecuteStateTransitionRequest{} }
func (m *ExecuteStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStateTransitionRequest) ProtoMessage()    {}
func (*ExecuteStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{2}
}
func (m *ExecuteStateTransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStateTransitionRequest.Unmarshal(m, b)
}
func (m *ExecuteStateTransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStateTransitionRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteStateTransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStateTransitionRequest.Merge(m, src)
}
func (m *ExecuteStateTransitionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteStateTransitionRequest.Size(m)
}
func (m *ExecuteStateTransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStateTransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStateTransitionRequest proto.InternalMessageInfo

func (m *ExecuteStateTransitionRequest) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *ExecuteStateTransitionRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ExecuteStateTransitionRequest) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type ExecuteStateTransitionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStateTransitionResponse) Reset()         { *m = ExecuteStateTransitionResponse{} }
func (m *ExecuteStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteStateTransitionResponse) ProtoMessage()    {}
func (*ExecuteStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{3}
}
func (m *ExecuteStateTransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStateTransitionResponse.Unmarshal(m, b)
}
func (m *ExecuteStateTransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStateTransitionResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteStateTransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStateTransitionResponse.Merge(m, src)
}
func (m *ExecuteStateTransitionResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteStateTransitionResponse.Size(m)
}
func (m *ExecuteStateTransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStateTransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStateTransitionResponse proto.InternalMessageInfo

func (m *ExecuteStateTransitionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ExecuteStateTransitionResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Provisioner struct {
	PublicKeyBls         []byte   `protobuf:"bytes,1,opt,name=public_key_bls,json=publicKeyBls,proto3" json:"public_key_bls,omitempty"`
	Stakes               []*Stake `protobuf:"bytes,2,rep,name=stakes,proto3" json:"stakes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provisioner) Reset()         { *m = Provisioner{} }
func (m *Provisioner) String() string { return proto.CompactTextString(m) }
func (*Provisioner) ProtoMessage()    {}
func (*Provisioner) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{4}
}
func (m *Provisioner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provisioner.Unmarshal(m, b)
}
func (m *Provisioner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provisioner.Marshal(b, m, deterministic)
}
func (m *Provisioner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provisioner.Merge(m, src)
}
func (m *Provisioner) XXX_Size() int {
	return xxx_messageInfo_Provisioner.Size(m)
}
func (m *Provisioner) XXX_DiscardUnknown() {
	xxx_messageInfo_Provisioner.DiscardUnknown(m)
}

var xxx_messageInfo_Provisioner proto.InternalMessageInfo

func (m *Provisioner) GetPublicKeyBls() []byte {
	if m != nil {
		return m.PublicKeyBls
	}
	return nil
}

func (m *Provisioner) GetStakes() []*Stake {
	if m != nil {
		return m.Stakes
	}
	return nil
}

type Stake struct {
	Amount               uint64   `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	StartHeight          uint64   `protobuf:"fixed64,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight            uint64   `protobuf:"fixed64,3,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stake) Reset()         { *m = Stake{} }
func (m *Stake) String() string { return proto.CompactTextString(m) }
func (*Stake) ProtoMessage()    {}
func (*Stake) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{5}
}
func (m *Stake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stake.Unmarshal(m, b)
}
func (m *Stake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stake.Marshal(b, m, deterministic)
}
func (m *Stake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stake.Merge(m, src)
}
func (m *Stake) XXX_Size() int {
	return xxx_messageInfo_Stake.Size(m)
}
func (m *Stake) XXX_DiscardUnknown() {
	xxx_messageInfo_Stake.DiscardUnknown(m)
}

var xxx_messageInfo_Stake proto.InternalMessageInfo

func (m *Stake) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Stake) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *Stake) GetEndHeight() uint64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

type GetProvisionersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProvisionersRequest) Reset()         { *m = GetProvisionersRequest{} }
func (m *GetProvisionersRequest) String() string { return proto.CompactTextString(m) }
func (*GetProvisionersRequest) ProtoMessage()    {}
func (*GetProvisionersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{6}
}
func (m *GetProvisionersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProvisionersRequest.Unmarshal(m, b)
}
func (m *GetProvisionersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProvisionersRequest.Marshal(b, m, deterministic)
}
func (m *GetProvisionersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProvisionersRequest.Merge(m, src)
}
func (m *GetProvisionersRequest) XXX_Size() int {
	return xxx_messageInfo_GetProvisionersRequest.Size(m)
}
func (m *GetProvisionersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProvisionersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProvisionersRequest proto.InternalMessageInfo

type GetProvisionersResponse struct {
	Provisioners         []*Provisioner `protobuf:"bytes,1,rep,name=provisioners,proto3" json:"provisioners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetProvisionersResponse) Reset()         { *m = GetProvisionersResponse{} }
func (m *GetProvisionersResponse) String() string { return proto.CompactTextString(m) }
func (*GetProvisionersResponse) ProtoMessage()    {}
func (*GetProvisionersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{7}
}
func (m *GetProvisionersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProvisionersResponse.Unmarshal(m, b)
}
func (m *GetProvisionersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProvisionersResponse.Marshal(b, m, deterministic)
}
func (m *GetProvisionersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProvisionersResponse.Merge(m, src)
}
func (m *GetProvisionersResponse) XXX_Size() int {
	return xxx_messageInfo_GetProvisionersResponse.Size(m)
}
func (m *GetProvisionersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProvisionersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProvisionersResponse proto.InternalMessageInfo

func (m *GetProvisionersResponse) GetProvisioners() []*Provisioner {
	if m != nil {
		return m.Provisioners
	}
	return nil
}

func init() {
	proto.RegisterType((*VerifyStateTransitionRequest)(nil), "rusk.VerifyStateTransitionRequest")
	proto.RegisterType((*VerifyStateTransitionResponse)(nil), "rusk.VerifyStateTransitionResponse")
	proto.RegisterType((*ExecuteStateTransitionRequest)(nil), "rusk.ExecuteStateTransitionRequest")
	proto.RegisterType((*ExecuteStateTransitionResponse)(nil), "rusk.ExecuteStateTransitionResponse")
	proto.RegisterType((*Provisioner)(nil), "rusk.Provisioner")
	proto.RegisterType((*Stake)(nil), "rusk.Stake")
	proto.RegisterType((*GetProvisionersRequest)(nil), "rusk.GetProvisionersRequest")
	proto.RegisterType((*GetProvisionersResponse)(nil), "rusk.GetProvisionersResponse")
}

func init() { proto.RegisterFile("rusk.proto", fileDescriptor_211ec4e18343b18f) }

var fileDescriptor_211ec4e18343b18f = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xa6, 0xeb, 0x08, 0xf4, 0x1a, 0x86, 0x66, 0x89, 0x12, 0x55, 0x2b, 0x2a, 0xe9, 0x1e, 0x22,
	0xa4, 0x75, 0xd2, 0x10, 0x4f, 0xbc, 0x15, 0x21, 0x90, 0x10, 0x52, 0xe5, 0x4d, 0x08, 0xf1, 0x12,
	0x39, 0xc9, 0xad, 0xb1, 0x92, 0xc6, 0xc1, 0x76, 0x60, 0xfd, 0x3f, 0xfc, 0x50, 0x64, 0x3b, 0x65,
	0x2d, 0xb4, 0x7d, 0xe4, 0xed, 0xee, 0xbb, 0xcf, 0xdf, 0xdd, 0x7d, 0xb6, 0x0c, 0x20, 0x1b, 0x55,
	0x4c, 0x6b, 0x29, 0xb4, 0x20, 0xc7, 0x26, 0x1e, 0x02, 0xa6, 0xb9, 0x70, 0xc8, 0xb0, 0x97, 0xf0,
	0xac, 0x0d, 0x4f, 0x92, 0x92, 0x57, 0xd9, 0x7d, 0x7e, 0xaa, 0x25, 0xab, 0x14, 0x4b, 0x35, 0x17,
	0x55, 0x0b, 0x41, 0x81, 0x2b, 0xe5, 0xe2, 0x50, 0xc0, 0xd9, 0x17, 0x94, 0xfc, 0x76, 0x75, 0xad,
	0x99, 0xc6, 0x1b, 0xc3, 0xe5, 0x86, 0x4a, 0xf1, 0x7b, 0x83, 0x4a, 0x93, 0x09, 0x74, 0xf5, 0x9d,
	0x0a, 0x3a, 0xe3, 0x6e, 0xd4, 0xbf, 0x3a, 0x9d, 0xda, 0x29, 0x6e, 0xee, 0x15, 0xa9, 0xa9, 0x92,
	0x01, 0x78, 0x39, 0xf2, 0x45, 0xae, 0x83, 0xa3, 0x71, 0x27, 0xf2, 0x68, 0x9b, 0x11, 0x02, 0xc7,
	0x0a, 0x31, 0x0b, 0xba, 0xe3, 0x4e, 0xe4, 0x53, 0x1b, 0x87, 0x33, 0x18, 0xed, 0x69, 0xa8, 0x6a,
	0x51, 0x29, 0x24, 0x2f, 0xc1, 0xbf, 0x65, 0xbc, 0xc4, 0x2c, 0x4e, 0x59, 0x59, 0xba, 0xd6, 0x1e,
	0xed, 0x3b, 0xec, 0x9d, 0x81, 0xc2, 0x1a, 0x46, 0xef, 0xef, 0x30, 0x6d, 0x34, 0xfe, 0xaf, 0xa9,
	0x63, 0x78, 0xb1, 0xaf, 0x63, 0x3b, 0x76, 0x00, 0x8f, 0x54, 0x93, 0xa6, 0xa8, 0x4c, 0xdb, 0x4e,
	0xf4, 0x98, 0xae, 0x53, 0x32, 0x81, 0x27, 0x28, 0xa5, 0x90, 0xf1, 0x12, 0x95, 0x62, 0x0b, 0xb4,
	0xed, 0x7a, 0xd4, 0xb7, 0xe0, 0x67, 0x87, 0x85, 0x5f, 0xa1, 0x3f, 0x97, 0xe2, 0x07, 0x57, 0x5c,
	0x54, 0x28, 0xc9, 0x39, 0x9c, 0xd4, 0x4d, 0x52, 0xf2, 0x34, 0x2e, 0x70, 0x15, 0x27, 0xa5, 0x13,
	0xf5, 0xa9, 0xef, 0xd0, 0x4f, 0xb8, 0x9a, 0x95, 0x46, 0xd9, 0x53, 0x9a, 0x15, 0xa8, 0x82, 0x23,
	0xbb, 0x69, 0xdf, 0x6d, 0x7a, 0x6d, 0x30, 0xda, 0x96, 0x42, 0x06, 0x0f, 0x2d, 0x60, 0xf6, 0x65,
	0x4b, 0xd1, 0x54, 0xda, 0x6a, 0x79, 0xb4, 0xcd, 0x8c, 0xe1, 0x4a, 0x33, 0xa9, 0xe3, 0x2d, 0x37,
	0xfa, 0x16, 0xfb, 0xe8, 0x2c, 0x19, 0x01, 0x60, 0x95, 0xad, 0x09, 0x5d, 0x4b, 0xe8, 0x61, 0x95,
	0xb9, 0x72, 0x18, 0xc0, 0xe0, 0x03, 0xea, 0x8d, 0xf9, 0x55, 0x7b, 0x11, 0xe1, 0x1c, 0x9e, 0xff,
	0x53, 0x69, 0x0d, 0x7b, 0x03, 0x7e, 0xbd, 0x81, 0x6f, 0x5f, 0xd6, 0xc6, 0x09, 0xba, 0x45, 0xbb,
	0xfa, 0x75, 0x64, 0xf7, 0xd1, 0x48, 0x12, 0x78, 0xb6, 0xf3, 0x25, 0x91, 0xd0, 0x69, 0x1c, 0x7a,
	0xd7, 0xc3, 0xc9, 0x41, 0x8e, 0x1b, 0x31, 0x7c, 0x40, 0x10, 0x06, 0xbb, 0xef, 0x9d, 0xb4, 0x02,
	0x07, 0xdf, 0xe1, 0xf0, 0xfc, 0x30, 0xe9, 0x4f, 0x9b, 0x39, 0x3c, 0xfd, 0xcb, 0x26, 0x72, 0xe6,
	0x8e, 0xee, 0xf6, 0x75, 0x38, 0xda, 0x53, 0x5d, 0x2b, 0xce, 0x5e, 0x7d, 0x8b, 0x16, 0x5c, 0xe7,
	0x4d, 0x32, 0x4d, 0xc5, 0xf2, 0x32, 0x6b, 0x54, 0x71, 0x51, 0xa1, 0xfe, 0x29, 0x64, 0x71, 0x69,
	0x4e, 0x5e, 0xa8, 0x34, 0xc7, 0x25, 0x7b, 0x6b, 0xe2, 0xc4, 0xb3, 0x5f, 0xc1, 0xeb, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0xe4, 0xf8, 0xfb, 0x64, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StateClient is the client API for State service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateClient interface {
	VerifyStateTransition(ctx context.Context, in *VerifyStateTransitionRequest, opts ...grpc.CallOption) (*VerifyStateTransitionResponse, error)
	ExecuteStateTransition(ctx context.Context, in *ExecuteStateTransitionRequest, opts ...grpc.CallOption) (*ExecuteStateTransitionResponse, error)
	GetProvisioners(ctx context.Context, in *GetProvisionersRequest, opts ...grpc.CallOption) (*GetProvisionersResponse, error)
}

type stateClient struct {
	cc *grpc.ClientConn
}

func NewStateClient(cc *grpc.ClientConn) StateClient {
	return &stateClient{cc}
}

func (c *stateClient) VerifyStateTransition(ctx context.Context, in *VerifyStateTransitionRequest, opts ...grpc.CallOption) (*VerifyStateTransitionResponse, error) {
	out := new(VerifyStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/rusk.State/VerifyStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) ExecuteStateTransition(ctx context.Context, in *ExecuteStateTransitionRequest, opts ...grpc.CallOption) (*ExecuteStateTransitionResponse, error) {
	out := new(ExecuteStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/rusk.State/ExecuteStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetProvisioners(ctx context.Context, in *GetProvisionersRequest, opts ...grpc.CallOption) (*GetProvisionersResponse, error) {
	out := new(GetProvisionersResponse)
	err := c.cc.Invoke(ctx, "/rusk.State/GetProvisioners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServer is the server API for State service.
type StateServer interface {
	VerifyStateTransition(context.Context, *VerifyStateTransitionRequest) (*VerifyStateTransitionResponse, error)
	ExecuteStateTransition(context.Context, *ExecuteStateTransitionRequest) (*ExecuteStateTransitionResponse, error)
	GetProvisioners(context.Context, *GetProvisionersRequest) (*GetProvisionersResponse, error)
}

// UnimplementedStateServer can be embedded to have forward compatible implementations.
type UnimplementedStateServer struct {
}

func (*UnimplementedStateServer) VerifyStateTransition(ctx context.Context, req *VerifyStateTransitionRequest) (*VerifyStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyStateTransition not implemented")
}
func (*UnimplementedStateServer) ExecuteStateTransition(ctx context.Context, req *ExecuteStateTransitionRequest) (*ExecuteStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteStateTransition not implemented")
}
func (*UnimplementedStateServer) GetProvisioners(ctx context.Context, req *GetProvisionersRequest) (*GetProvisionersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvisioners not implemented")
}

func RegisterStateServer(s *grpc.Server, srv StateServer) {
	s.RegisterService(&_State_serviceDesc, srv)
}

func _State_VerifyStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).VerifyStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.State/VerifyStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).VerifyStateTransition(ctx, req.(*VerifyStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_ExecuteStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).ExecuteStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.State/ExecuteStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).ExecuteStateTransition(ctx, req.(*ExecuteStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetProvisioners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvisionersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetProvisioners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.State/GetProvisioners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetProvisioners(ctx, req.(*GetProvisionersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _State_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rusk.State",
	HandlerType: (*StateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyStateTransition",
			Handler:    _State_VerifyStateTransition_Handler,
		},
		{
			MethodName: "ExecuteStateTransition",
			Handler:    _State_ExecuteStateTransition_Handler,
		},
		{
			MethodName: "GetProvisioners",
			Handler:    _State_GetProvisioners_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rusk.proto",
}
