// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transfer.proto

package rusk

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TransferMock struct{}

func (m *TransferMock) NewTransfer(ctx context.Context, req *TransferTransactionRequest) (*Transaction, error) {
	res :=
		&Transaction{
			Version: 199,
			Type:    784,
			TxPayload: &TransactionPayload{
				Anchor: &BlsScalar{},
				Nullifier: []*BlsScalar{
					&BlsScalar{},
					&BlsScalar{},
					&BlsScalar{},
					&BlsScalar{},
					&BlsScalar{},
					&BlsScalar{},
					&BlsScalar{},
					&BlsScalar{},
				},
				Crossover: &Crossover{
					ValueComm:    &JubJubCompressed{},
					Nonce:        &BlsScalar{},
					EncyptedData: &PoseidonCipher{},
				},
				Notes: []*Note{
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
					&Note{
						Randomness:   &JubJubCompressed{},
						PkR:          &JubJubCompressed{},
						Commitment:   &JubJubCompressed{},
						Nonce:        &BlsScalar{},
						EncyptedData: &PoseidonCipher{},
					},
				},
				Fee: &Fee{
					GasLimit: 534,
					GasPrice: 232,
					R:        &JubJubCompressed{},
					PkR:      &JubJubCompressed{},
				},
				SpendingProof: &Proof{},
			},
		}
	return res, nil
}
