// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction.proto

package rusk

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Crossover struct {
	ValueComm            *JubJubCompressed `protobuf:"bytes,1,opt,name=value_comm,json=valueComm,proto3" json:"value_comm,omitempty"`
	Nonce                *BlsScalar        `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EncyptedData         *PoseidonCipher   `protobuf:"bytes,3,opt,name=encypted_data,json=encyptedData,proto3" json:"encypted_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Crossover) Reset()         { *m = Crossover{} }
func (m *Crossover) String() string { return proto.CompactTextString(m) }
func (*Crossover) ProtoMessage()    {}
func (*Crossover) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}
func (m *Crossover) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crossover.Unmarshal(m, b)
}
func (m *Crossover) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crossover.Marshal(b, m, deterministic)
}
func (m *Crossover) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crossover.Merge(m, src)
}
func (m *Crossover) XXX_Size() int {
	return xxx_messageInfo_Crossover.Size(m)
}
func (m *Crossover) XXX_DiscardUnknown() {
	xxx_messageInfo_Crossover.DiscardUnknown(m)
}

var xxx_messageInfo_Crossover proto.InternalMessageInfo

func (m *Crossover) GetValueComm() *JubJubCompressed {
	if m != nil {
		return m.ValueComm
	}
	return nil
}

func (m *Crossover) GetNonce() *BlsScalar {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Crossover) GetEncyptedData() *PoseidonCipher {
	if m != nil {
		return m.EncyptedData
	}
	return nil
}

type Fee struct {
	GasLimit             uint64            `protobuf:"varint,1,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice             uint64            `protobuf:"varint,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	R                    *JubJubCompressed `protobuf:"bytes,3,opt,name=R,proto3" json:"R,omitempty"`
	PkR                  *JubJubCompressed `protobuf:"bytes,4,opt,name=pk_r,json=pkR,proto3" json:"pk_r,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Fee) Reset()         { *m = Fee{} }
func (m *Fee) String() string { return proto.CompactTextString(m) }
func (*Fee) ProtoMessage()    {}
func (*Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}
func (m *Fee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fee.Unmarshal(m, b)
}
func (m *Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fee.Marshal(b, m, deterministic)
}
func (m *Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fee.Merge(m, src)
}
func (m *Fee) XXX_Size() int {
	return xxx_messageInfo_Fee.Size(m)
}
func (m *Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_Fee proto.InternalMessageInfo

func (m *Fee) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Fee) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *Fee) GetR() *JubJubCompressed {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Fee) GetPkR() *JubJubCompressed {
	if m != nil {
		return m.PkR
	}
	return nil
}

type Note struct {
	Randomness           *JubJubCompressed `protobuf:"bytes,1,opt,name=randomness,proto3" json:"randomness,omitempty"`
	PkR                  *JubJubCompressed `protobuf:"bytes,2,opt,name=pk_r,json=pkR,proto3" json:"pk_r,omitempty"`
	Commitment           *JubJubCompressed `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	Nonce                *BlsScalar        `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EncyptedData         *PoseidonCipher   `protobuf:"bytes,5,opt,name=encypted_data,json=encyptedData,proto3" json:"encypted_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}
func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (m *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(m, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetRandomness() *JubJubCompressed {
	if m != nil {
		return m.Randomness
	}
	return nil
}

func (m *Note) GetPkR() *JubJubCompressed {
	if m != nil {
		return m.PkR
	}
	return nil
}

func (m *Note) GetCommitment() *JubJubCompressed {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *Note) GetNonce() *BlsScalar {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Note) GetEncyptedData() *PoseidonCipher {
	if m != nil {
		return m.EncyptedData
	}
	return nil
}

type TransactionPayload struct {
	Anchor               *BlsScalar   `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Nullifier            []*BlsScalar `protobuf:"bytes,2,rep,name=nullifier,proto3" json:"nullifier,omitempty"`
	Crossover            *Crossover   `protobuf:"bytes,3,opt,name=crossover,proto3" json:"crossover,omitempty"`
	Notes                []*Note      `protobuf:"bytes,4,rep,name=notes,proto3" json:"notes,omitempty"`
	Fee                  *Fee         `protobuf:"bytes,5,opt,name=fee,proto3" json:"fee,omitempty"`
	SpendingProof        *Proof       `protobuf:"bytes,6,opt,name=spending_proof,json=spendingProof,proto3" json:"spending_proof,omitempty"`
	CallData             []byte       `protobuf:"bytes,7,opt,name=call_data,json=callData,proto3" json:"call_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransactionPayload) Reset()         { *m = TransactionPayload{} }
func (m *TransactionPayload) String() string { return proto.CompactTextString(m) }
func (*TransactionPayload) ProtoMessage()    {}
func (*TransactionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}
func (m *TransactionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionPayload.Unmarshal(m, b)
}
func (m *TransactionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionPayload.Marshal(b, m, deterministic)
}
func (m *TransactionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionPayload.Merge(m, src)
}
func (m *TransactionPayload) XXX_Size() int {
	return xxx_messageInfo_TransactionPayload.Size(m)
}
func (m *TransactionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionPayload proto.InternalMessageInfo

func (m *TransactionPayload) GetAnchor() *BlsScalar {
	if m != nil {
		return m.Anchor
	}
	return nil
}

func (m *TransactionPayload) GetNullifier() []*BlsScalar {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *TransactionPayload) GetCrossover() *Crossover {
	if m != nil {
		return m.Crossover
	}
	return nil
}

func (m *TransactionPayload) GetNotes() []*Note {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *TransactionPayload) GetFee() *Fee {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *TransactionPayload) GetSpendingProof() *Proof {
	if m != nil {
		return m.SpendingProof
	}
	return nil
}

func (m *TransactionPayload) GetCallData() []byte {
	if m != nil {
		return m.CallData
	}
	return nil
}

type Transaction struct {
	Version              uint32              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type                 uint32              `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	TxPayload            *TransactionPayload `protobuf:"bytes,3,opt,name=tx_payload,json=txPayload,proto3" json:"tx_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetTxPayload() *TransactionPayload {
	if m != nil {
		return m.TxPayload
	}
	return nil
}

func init() {
	proto.RegisterType((*Crossover)(nil), "rusk.Crossover")
	proto.RegisterType((*Fee)(nil), "rusk.Fee")
	proto.RegisterType((*Note)(nil), "rusk.Note")
	proto.RegisterType((*TransactionPayload)(nil), "rusk.TransactionPayload")
	proto.RegisterType((*Transaction)(nil), "rusk.Transaction")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x8b, 0x13, 0x31,
	0x14, 0xc7, 0x99, 0x76, 0xb6, 0xbb, 0xf3, 0xba, 0x55, 0x0c, 0x22, 0x83, 0x7b, 0x29, 0x45, 0xb1,
	0x0a, 0xed, 0xc2, 0x8a, 0x8a, 0x78, 0xdb, 0xca, 0x1e, 0x16, 0x91, 0x12, 0x3d, 0x79, 0x19, 0xd2,
	0x99, 0xd7, 0x36, 0x74, 0x26, 0x09, 0x49, 0xa6, 0x6e, 0xcf, 0x7e, 0x01, 0x3f, 0x84, 0x37, 0xbf,
	0xa4, 0x24, 0x99, 0x6e, 0x0b, 0xab, 0x56, 0x6f, 0x79, 0xf9, 0xff, 0xde, 0xbc, 0xbc, 0xff, 0x7b,
	0x0c, 0x3c, 0xb0, 0x9a, 0x09, 0xc3, 0x72, 0xcb, 0xa5, 0x18, 0x2b, 0x2d, 0xad, 0x24, 0xb1, 0xae,
	0xcd, 0xea, 0x31, 0x99, 0x31, 0xc3, 0xf3, 0x6c, 0xce, 0xb1, 0x2c, 0x4c, 0x50, 0x06, 0x3f, 0x22,
	0x48, 0x26, 0x5a, 0x1a, 0x23, 0xd7, 0xa8, 0xc9, 0x2b, 0x80, 0x35, 0x2b, 0x6b, 0xcc, 0x72, 0x59,
	0x55, 0x69, 0xd4, 0x8f, 0x86, 0xdd, 0x8b, 0x47, 0x63, 0x97, 0x3c, 0xbe, 0xae, 0x67, 0xd7, 0xf5,
	0x6c, 0x22, 0x2b, 0xa5, 0xd1, 0x18, 0x2c, 0x68, 0xe2, 0xc9, 0x89, 0xac, 0x2a, 0xf2, 0x14, 0x8e,
	0x84, 0x14, 0x39, 0xa6, 0x2d, 0x9f, 0x71, 0x3f, 0x64, 0x5c, 0x96, 0xe6, 0x53, 0xce, 0x4a, 0xa6,
	0x69, 0x50, 0xc9, 0x5b, 0xe8, 0xa1, 0xc8, 0x37, 0xca, 0x62, 0x91, 0x15, 0xcc, 0xb2, 0xb4, 0xed,
	0xf1, 0x87, 0x01, 0x9f, 0x4a, 0x83, 0xbc, 0x90, 0x62, 0xc2, 0xd5, 0x12, 0x35, 0x3d, 0xdd, 0xa2,
	0xef, 0x99, 0x65, 0x83, 0xef, 0x11, 0xb4, 0xaf, 0x10, 0xc9, 0x19, 0x24, 0x0b, 0x66, 0xb2, 0x92,
	0x57, 0xdc, 0xfa, 0xf7, 0xc5, 0xf4, 0x64, 0xc1, 0xcc, 0x07, 0x17, 0x6f, 0x45, 0xa5, 0x79, 0xf3,
	0x94, 0x20, 0x4e, 0x5d, 0x4c, 0x9e, 0x40, 0x44, 0x9b, 0x82, 0x7f, 0xea, 0x28, 0xa2, 0xe4, 0x39,
	0xc4, 0x6a, 0x95, 0xe9, 0x34, 0xfe, 0x2b, 0xd8, 0x56, 0x2b, 0x3a, 0xf8, 0xd6, 0x82, 0xf8, 0xa3,
	0xb4, 0x48, 0x5e, 0x03, 0x68, 0x26, 0x0a, 0x59, 0x09, 0x34, 0xe6, 0x80, 0x69, 0x7b, 0xe4, 0x6d,
	0xad, 0xd6, 0xc1, 0x5a, 0xae, 0x84, 0x9b, 0x08, 0xb7, 0x15, 0x0a, 0x7b, 0xa0, 0x8b, 0x3d, 0x72,
	0x37, 0x98, 0xf8, 0xff, 0x06, 0x73, 0xf4, 0xcf, 0x83, 0xf9, 0xd9, 0x02, 0xf2, 0x79, 0xb7, 0x6f,
	0x53, 0xb6, 0x29, 0x25, 0x2b, 0xc8, 0x33, 0xe8, 0x30, 0x91, 0x2f, 0xa5, 0x6e, 0xfc, 0xb8, 0x53,
	0xb9, 0x91, 0xc9, 0x08, 0x12, 0x51, 0x97, 0x25, 0x9f, 0x73, 0x74, 0x4e, 0xb4, 0x7f, 0xc7, 0xee,
	0x08, 0x87, 0xe7, 0xdb, 0x6d, 0x6d, 0x7c, 0x68, 0xf0, 0xdb, 0x25, 0xa6, 0x3b, 0x82, 0xf4, 0x5d,
	0xff, 0x16, 0x4d, 0x1a, 0xfb, 0x2f, 0x43, 0x40, 0xdd, 0xd4, 0x68, 0x10, 0xc8, 0x19, 0xb4, 0xe7,
	0x88, 0x4d, 0xc3, 0x49, 0xd0, 0xaf, 0x10, 0xa9, 0xbb, 0x25, 0x17, 0x70, 0xcf, 0x28, 0x14, 0x05,
	0x17, 0x8b, 0x4c, 0x69, 0x29, 0xe7, 0x69, 0xc7, 0x73, 0xdd, 0xc6, 0x18, 0x77, 0x45, 0x7b, 0x5b,
	0xc4, 0x87, 0x6e, 0x09, 0x73, 0x56, 0x96, 0xc1, 0xc7, 0xe3, 0x7e, 0x34, 0x3c, 0xa5, 0x27, 0xee,
	0xc2, 0xbb, 0x65, 0xa1, 0xbb, 0x67, 0x16, 0x49, 0xe1, 0x78, 0x8d, 0xda, 0x70, 0x29, 0xbc, 0x4d,
	0x3d, 0xba, 0x0d, 0x09, 0x81, 0xd8, 0x6e, 0x54, 0xd8, 0xe2, 0x1e, 0xf5, 0x67, 0xf2, 0x06, 0xc0,
	0xde, 0x64, 0x2a, 0x38, 0xdc, 0x34, 0x9f, 0x86, 0x97, 0xdc, 0x9d, 0x00, 0x4d, 0xec, 0x4d, 0x73,
	0xbc, 0x7c, 0xf1, 0x65, 0xb8, 0xe0, 0x76, 0x59, 0xcf, 0xc6, 0xb9, 0xac, 0xce, 0x8b, 0xda, 0xac,
	0x46, 0x02, 0xed, 0x57, 0xa9, 0x57, 0xe7, 0x2e, 0x7b, 0x64, 0xf2, 0x25, 0x56, 0xec, 0x9d, 0x3b,
	0xcf, 0x3a, 0xfe, 0xb7, 0xf0, 0xf2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x3f, 0x10, 0xde,
	0x45, 0x04, 0x00, 0x00,
}
