// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package rusk

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Note_NoteType int32

const (
	Note_TRANSPARENT Note_NoteType = 0
	Note_OBFUSCATED  Note_NoteType = 1
)

var Note_NoteType_name = map[int32]string{
	0: "TRANSPARENT",
	1: "OBFUSCATED",
}

var Note_NoteType_value = map[string]int32{
	"TRANSPARENT": 0,
	"OBFUSCATED":  1,
}

func (x Note_NoteType) String() string {
	return proto.EnumName(Note_NoteType_name, int32(x))
}

func (Note_NoteType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2, 0}
}

type Crossover struct {
	ValueCommitment      []byte   `protobuf:"bytes,1,opt,name=value_commitment,json=valueCommitment,proto3" json:"value_commitment,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EncryptedData        []byte   `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crossover) Reset()         { *m = Crossover{} }
func (m *Crossover) String() string { return proto.CompactTextString(m) }
func (*Crossover) ProtoMessage()    {}
func (*Crossover) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Crossover) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crossover.Unmarshal(m, b)
}
func (m *Crossover) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crossover.Marshal(b, m, deterministic)
}
func (m *Crossover) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crossover.Merge(m, src)
}
func (m *Crossover) XXX_Size() int {
	return xxx_messageInfo_Crossover.Size(m)
}
func (m *Crossover) XXX_DiscardUnknown() {
	xxx_messageInfo_Crossover.DiscardUnknown(m)
}

var xxx_messageInfo_Crossover proto.InternalMessageInfo

func (m *Crossover) GetValueCommitment() []byte {
	if m != nil {
		return m.ValueCommitment
	}
	return nil
}

func (m *Crossover) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Crossover) GetEncryptedData() []byte {
	if m != nil {
		return m.EncryptedData
	}
	return nil
}

type Fee struct {
	GasLimit             uint64          `protobuf:"varint,1,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice             uint64          `protobuf:"varint,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	StealthAddress       *StealthAddress `protobuf:"bytes,3,opt,name=stealth_address,json=stealthAddress,proto3" json:"stealth_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Fee) Reset()         { *m = Fee{} }
func (m *Fee) String() string { return proto.CompactTextString(m) }
func (*Fee) ProtoMessage()    {}
func (*Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *Fee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fee.Unmarshal(m, b)
}
func (m *Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fee.Marshal(b, m, deterministic)
}
func (m *Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fee.Merge(m, src)
}
func (m *Fee) XXX_Size() int {
	return xxx_messageInfo_Fee.Size(m)
}
func (m *Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_Fee proto.InternalMessageInfo

func (m *Fee) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Fee) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *Fee) GetStealthAddress() *StealthAddress {
	if m != nil {
		return m.StealthAddress
	}
	return nil
}

type Note struct {
	NoteType             Note_NoteType   `protobuf:"varint,1,opt,name=note_type,json=noteType,proto3,enum=rusk.Note_NoteType" json:"note_type,omitempty"`
	ValueCommitment      []byte          `protobuf:"bytes,2,opt,name=value_commitment,json=valueCommitment,proto3" json:"value_commitment,omitempty"`
	Nonce                []byte          `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	StealthAddress       *StealthAddress `protobuf:"bytes,4,opt,name=stealth_address,json=stealthAddress,proto3" json:"stealth_address,omitempty"`
	Pos                  uint64          `protobuf:"fixed64,5,opt,name=pos,proto3" json:"pos,omitempty"`
	EncryptedData        []byte          `protobuf:"bytes,6,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (m *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(m, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetNoteType() Note_NoteType {
	if m != nil {
		return m.NoteType
	}
	return Note_TRANSPARENT
}

func (m *Note) GetValueCommitment() []byte {
	if m != nil {
		return m.ValueCommitment
	}
	return nil
}

func (m *Note) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Note) GetStealthAddress() *StealthAddress {
	if m != nil {
		return m.StealthAddress
	}
	return nil
}

func (m *Note) GetPos() uint64 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *Note) GetEncryptedData() []byte {
	if m != nil {
		return m.EncryptedData
	}
	return nil
}

type Transaction struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TransactionRequest struct {
	ContractAddress      []byte   `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	OpCode               uint32   `protobuf:"varint,2,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	Arguments            []byte   `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Fee                  *Fee     `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *TransactionRequest) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *TransactionRequest) GetArguments() []byte {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *TransactionRequest) GetFee() *Fee {
	if m != nil {
		return m.Fee
	}
	return nil
}

func init() {
	proto.RegisterEnum("rusk.Note_NoteType", Note_NoteType_name, Note_NoteType_value)
	proto.RegisterType((*Crossover)(nil), "rusk.Crossover")
	proto.RegisterType((*Fee)(nil), "rusk.Fee")
	proto.RegisterType((*Note)(nil), "rusk.Note")
	proto.RegisterType((*Transaction)(nil), "rusk.Transaction")
	proto.RegisterType((*TransactionRequest)(nil), "rusk.TransactionRequest")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6b, 0xdb, 0x30,
	0x14, 0xc6, 0x9b, 0xd8, 0x4d, 0xe3, 0x97, 0xd5, 0x49, 0xb5, 0xc2, 0x4c, 0xbb, 0x43, 0x31, 0x0c,
	0x3a, 0x06, 0x61, 0x64, 0xe7, 0x31, 0xb2, 0xb4, 0x39, 0x8d, 0xac, 0x28, 0xce, 0xd9, 0x68, 0xf6,
	0x5b, 0x66, 0x9a, 0x48, 0x9e, 0xa4, 0x64, 0xf8, 0xb2, 0x7f, 0x62, 0xf7, 0xfd, 0xad, 0x43, 0x92,
	0x9d, 0x36, 0x34, 0xb0, 0x5e, 0x8c, 0xbe, 0xef, 0xb3, 0xf5, 0xde, 0xfb, 0xf1, 0x0c, 0x67, 0x5a,
	0x32, 0xae, 0x58, 0xa6, 0x0b, 0xc1, 0x87, 0xa5, 0x14, 0x5a, 0x10, 0x5f, 0x6e, 0xd4, 0xfd, 0x05,
	0xdc, 0x63, 0xa5, 0x9c, 0x13, 0x2b, 0x08, 0x26, 0x52, 0x28, 0x25, 0xb6, 0x28, 0xc9, 0x5b, 0x18,
	0x6c, 0xd9, 0x6a, 0x83, 0x69, 0x26, 0xd6, 0xeb, 0x42, 0xaf, 0x91, 0xeb, 0xa8, 0x75, 0xd5, 0xba,
	0x7e, 0x41, 0xfb, 0xd6, 0x9f, 0xec, 0x6c, 0x72, 0x0e, 0xc7, 0x5c, 0xf0, 0x0c, 0xa3, 0xb6, 0xcd,
	0x9d, 0x20, 0x6f, 0x20, 0x44, 0x9e, 0xc9, 0xaa, 0xd4, 0x98, 0xa7, 0x39, 0xd3, 0x2c, 0xf2, 0x6c,
	0x7c, 0xba, 0x73, 0x6f, 0x98, 0x66, 0xf1, 0x6f, 0xf0, 0xa6, 0x88, 0xe4, 0x12, 0x82, 0x25, 0x53,
	0xe9, 0xaa, 0x58, 0x17, 0xae, 0x8e, 0x4f, 0xbb, 0x4b, 0xa6, 0xbe, 0x18, 0xdd, 0x84, 0xa5, 0x2c,
	0xea, 0x22, 0x2e, 0xbc, 0x33, 0x9a, 0x7c, 0x84, 0xbe, 0xd2, 0xc8, 0x56, 0xfa, 0x47, 0xca, 0xf2,
	0x5c, 0xa2, 0x52, 0xb6, 0x50, 0x6f, 0x74, 0x3e, 0x34, 0x13, 0x0e, 0xe7, 0x2e, 0x1c, 0xbb, 0x8c,
	0x86, 0x6a, 0x4f, 0xc7, 0x7f, 0xdb, 0xe0, 0xcf, 0x84, 0x46, 0xf2, 0x1e, 0x02, 0x2e, 0x34, 0xa6,
	0xba, 0x2a, 0xd1, 0x76, 0x10, 0x8e, 0x5e, 0xba, 0x1b, 0x4c, 0x6c, 0x1f, 0x49, 0x55, 0x22, 0xed,
	0xf2, 0xfa, 0x74, 0x10, 0x51, 0xfb, 0x3f, 0x88, 0xbc, 0xc7, 0x88, 0x0e, 0xb4, 0xee, 0x3f, 0xbf,
	0x75, 0x32, 0x00, 0xaf, 0x14, 0x2a, 0x3a, 0xbe, 0x6a, 0x5d, 0x77, 0xa8, 0x39, 0x1e, 0x60, 0xde,
	0x39, 0xc4, 0xfc, 0x1d, 0x74, 0x9b, 0x71, 0x48, 0x1f, 0x7a, 0x09, 0x1d, 0xcf, 0xe6, 0x77, 0x63,
	0x7a, 0x3b, 0x4b, 0x06, 0x47, 0x24, 0x04, 0xf8, 0xfa, 0x79, 0xba, 0x98, 0x4f, 0xc6, 0xc9, 0xed,
	0xcd, 0xa0, 0x15, 0x2f, 0xa0, 0x97, 0x3c, 0x2c, 0x0f, 0x89, 0xe0, 0x64, 0x8b, 0x52, 0x15, 0x82,
	0x5b, 0x48, 0xa7, 0xb4, 0x91, 0x84, 0x80, 0x6f, 0xd9, 0xb5, 0xad, 0x6d, 0xcf, 0xe6, 0xed, 0x92,
	0x55, 0x2b, 0xc1, 0xf2, 0x7a, 0xf2, 0x46, 0xc6, 0x7f, 0x5a, 0x40, 0x1e, 0xdd, 0x4b, 0xf1, 0xe7,
	0x06, 0x95, 0x36, 0x4c, 0x33, 0xc1, 0xb5, 0x64, 0x99, 0xde, 0x31, 0xa9, 0xd7, 0xae, 0xf1, 0x9b,
	0xf1, 0x5f, 0xc1, 0x89, 0x28, 0xd3, 0x4c, 0xe4, 0x4d, 0xc9, 0x8e, 0x28, 0x27, 0x22, 0x47, 0xf2,
	0x1a, 0x02, 0x26, 0x97, 0x1b, 0x03, 0x5e, 0xd5, 0x65, 0x1f, 0x0c, 0x72, 0x09, 0xde, 0x77, 0xc4,
	0x1a, 0x74, 0xe0, 0x40, 0x4f, 0x11, 0xa9, 0x71, 0x47, 0x8b, 0xbd, 0xa6, 0xe6, 0x28, 0xb7, 0x66,
	0xc5, 0x3e, 0x41, 0x38, 0xc3, 0x5f, 0x7b, 0x14, 0xdc, 0x77, 0x4f, 0x07, 0xb8, 0x38, 0x7b, 0x92,
	0xc4, 0x47, 0xdf, 0x3a, 0xf6, 0x07, 0xfb, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x7a, 0x5b,
	0xf7, 0x87, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	// A generic method to create a transaction which requires
	// no special fields (no crossover, outputs, or specific proofs).
	NewTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) NewTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/rusk.TransactionService/NewTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	// A generic method to create a transaction which requires
	// no special fields (no crossover, outputs, or specific proofs).
	NewTransaction(context.Context, *TransactionRequest) (*Transaction, error)
}

// UnimplementedTransactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (*UnimplementedTransactionServiceServer) NewTransaction(ctx context.Context, req *TransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTransaction not implemented")
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_NewTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).NewTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusk.TransactionService/NewTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).NewTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rusk.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTransaction",
			Handler:    _TransactionService_NewTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
